version: "3.9"
services:
  backend:
    build: ./backend
    container_name: platform_backend
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - platform_net

  frontend:
    build: ./frontend
    container_name: platform_frontend
    ports:
      - "5173:80"
    networks:
      - platform_net

networks:
  platform_net:
